UP-2685 - Adjusts styles for expanded response
35up/RapiDoc pull request #2
Opened 2022-03-16 12:25 UTC by gustavoaz7

2022-03-16 17:02 UTC, uschischroder approved these changes

2022-03-17 13:36 UTC, enjoythelive1 requested changes
The CI should install the dependencies using `npm ci`

2022-03-17 13:36 UTC, enjoythelive1 commented on Makefile
> +ci: lint build
```suggestion
.PHONY: node_modules
node_modules:
	npm i

.PHONY: build
build:
	npm run build

.PHONY: lint
lint:
	npm run lint

.PHONY: ci
ci: node_modules lint build
```

2022-03-25 09:33 UTC, Drafter500 commented
The actions have not been run in this branch, do we miss something here?

2022-03-25 09:39 UTC, gustavoaz7 commented
> The actions have not been run in this branch, do we miss something here?

They have. Here is one example https://github.com/35up/RapiDoc/actions/runs/1998585647
I guess latest commit did not due to late github issues as victor mentioned in the standup

2022-03-25 13:21 UTC, enjoythelive1 approved these changes

2022-03-25 14:36 UTC, Drafter500 approved these changes

2022-03-25 14:37 UTC, merged