UP-3347 - Enhances UI
35up/RapiDoc pull request #4
Opened 2022-07-28 10:33 UTC by gustavoaz7

| Feedback  | Before | After |
| --------- | ------ | ----- |
| Schema description text cut when single line mode | <img width="566" alt="Screenshot 2022-07-27 at 16 13 26" src="https://user-images.githubusercontent.com/28453820/181275734-5c500f34-1b5f-402c-9b78-d0324d265279.png"> | <img width="577" alt="Screenshot 2022-07-27 at 16 11 03" src="https://user-images.githubusercontent.com/28453820/181275805-7e01d500-e78e-419a-bcab-d2390647a7a4.png"> |
| Strange url with dashes | `http://localhost:8080/#get-/products/-sku-` | `http://localhost:8080/#get/products/<sku>` |
| Auth info placed at the bottom | <img width="458" alt="Screenshot 2022-07-27 at 16 14 56" src="https://user-images.githubusercontent.com/28453820/181276629-2b3dd7c0-8fea-4347-820c-f1289a787db0.png"> | <img width="460" alt="Screenshot 2022-07-27 at 16 08 57" src="https://user-images.githubusercontent.com/28453820/181276671-6ea8686e-5381-45d0-844f-388d06e04521.png"> |
| Extra horizontal padding for inline `code` element | <img width="440" alt="Screenshot 2022-07-27 at 16 14 12" src="https://user-images.githubusercontent.com/28453820/181277066-5087cc13-21e3-446c-abfb-fbff43e87157.png"> | <img width="434" alt="Screenshot 2022-07-27 at 16 09 55" src="https://user-images.githubusercontent.com/28453820/181277137-69404c3a-c94a-4e1a-b049-bab284c64b08.png"> |
| Allow user to view request parameters as schema | <img width="575" alt="Screenshot 2022-07-28 at 12 28 37" src="https://user-images.githubusercontent.com/28453820/181484874-a0ae07d8-4a1b-4c9e-8c6c-a352067ee747.png"> | <img width="572" alt="Screenshot 2022-07-28 at 12 27 04" src="https://user-images.githubusercontent.com/28453820/181484928-ca6ee085-21d5-4056-80d4-a3ac84734bdf.png"> |

## Feedback's feedback

IMO auth info made more sense in the previous context

2022-08-02 07:08 UTC, uschischroder approved these changes

2022-08-04 07:53 UTC, enjoythelive1 requested changes

2022-08-04 07:53 UTC, enjoythelive1 commented on src/styles/schema-styles.js
> +    -webkit-line-clamp: 1;
This is not standard css. This does not work in firefox

2022-08-04 07:53 UTC, enjoythelive1 commented on src/components/api-request.js
> +      const paramsSchemaAsObj = schemaInObjectNotation(paramsSchema, {});
I think this should be extracted to a function outside of this context

2022-08-04 07:53 UTC, enjoythelive1 commented on src/components/api-request.js
> +          schema-hide-write-only = "false"
```suggestion
          class='json'
          style='display: block'
          .data='${paramsSchemaAsObj}'
          schema-expand-level="${this.schemaExpandLevel}"
          schema-description-expanded="${this.schemaDescriptionExpanded}"
          allow-schema-description-expand-toggle="${this.allowSchemaDescriptionExpandToggle}",
          schema-hide-read-only="${this.schemaHideReadOnly.includes(this.method)}"
          schema-hide-write-only="false"
```

2022-08-04 07:53 UTC, enjoythelive1 commented on src/components/api-request.js
> +          this.activeParameterTemplateTabs = newState;
```suggestion
          this.activeParameterTemplateTabs =  { ...this.activeParameterTemplateTabs, [paramType]: e.target.dataset.tab};
```

2022-08-04 07:53 UTC, enjoythelive1 commented on src/components/api-request.js
> +        <button class="tab-btn ${this.activeParameterTemplateTabs[paramType] !== 'schema' ? 'active' : ''}" data-tab = 'interactive'>INTERACTIVE </button>
Any reason you took this approach?  Do youj need the `data-tab` for something else?

2022-08-04 08:14 UTC, gustavoaz7 commented on src/styles/schema-styles.js
> +    -webkit-line-clamp: 1;
Not true. Works for firefox since v68
https://caniuse.com/css-line-clamp

2022-08-04 08:24 UTC, gustavoaz7 commented
Answering most of the comments: 
Either I moved their code around or followed previous implementation (tabs) or followed rapidoc's formatting convention

2022-08-04 11:15 UTC, enjoythelive1 commented on src/components/api-request.js
> +        <button class="tab-btn ${this.activeParameterTemplateTabs[paramType] !== 'schema' ? 'active' : ''}" data-tab = 'interactive'>INTERACTIVE </button>
So, this is no new code?

2022-08-04 11:16 UTC, enjoythelive1 commented on src/components/api-request.js
> +          this.activeParameterTemplateTabs = newState;
I though you added the `activeParameterTemplateTabs` field

2022-08-04 11:51 UTC, gustavoaz7 commented on src/components/api-request.js
> +        <button class="tab-btn ${this.activeParameterTemplateTabs[paramType] !== 'schema' ? 'active' : ''}" data-tab = 'interactive'>INTERACTIVE </button>
It is

2022-08-08 14:47 UTC, Drafter500 commented on src/styles/font-styles.js
> +    padding: 1px 0;
that should be possible to do from ogma.

2022-08-08 14:48 UTC, Drafter500 commented on src/components/schema-tree.js
> +          ${constraint ? html`<div style='line-break:anywhere; margin-right:8px'><span class='bold-text'>Constraints: </span>${constraint}</div>` : ''}
that should be possible to do from ogma

2022-08-08 14:56 UTC, Drafter500 commented on src/components/api-request.js
> +        <button class="tab-btn ${this.activeParameterTemplateTabs[paramType] !== 'example' ? 'active' : ''}" data-tab = 'interactive'>INTERACTIVE </button>
redundant space after `INTERACTIVE `

2022-08-08 15:57 UTC, gustavoaz7 commented on src/styles/font-styles.js
> +    padding: 1px 0;
I don't think so.
Not everything is configurable from the outside.
Rapidoc uses web-components so we are dealing with shadow-dom.
They do provide some [parts](https://rapidocweb.com/css-parts.html) to override style but that's not the case

2022-08-08 15:57 UTC, gustavoaz7 commented on src/components/schema-tree.js
> +          ${constraint ? html`<div style='line-break:anywhere; margin-right:8px'><span class='bold-text'>Constraints: </span>${constraint}</div>` : ''}
[same as above]

2022-08-08 16:46 UTC, Drafter500 commented
2 comments still not addressed

2022-08-08 17:59 UTC, gustavoaz7 commented
> 2 comments still not addressed

I have replied.

2022-08-09 14:19 UTC, Drafter500 approved these changes

2022-08-11 10:05 UTC, enjoythelive1 approved these changes

2022-08-11 17:52 UTC, merged