UP-3324 - Adds download yaml link
35up/RapiDoc pull request #5
Opened 2022-08-04 08:11 UTC by uschischroder

2022-08-04 08:39 UTC, enjoythelive1 requested changes

2022-08-04 08:39 UTC, enjoythelive1 commented on src/templates/navbar-template.js
> +      }}'>Download YAML file</button>
```suggestion
      <a 
        download="35up-specs.yml"
        href=${this.specUrl}
        class="m-btn thin-border" style="width:170px; margin: 0 auto;" part="btn btn-outline"
      >
        Download YAML file
      </a>
```
Wouldn't this be better? That way you don't need a click handler. Is it to avoid the underlining of the text of the links?

2022-08-04 13:06 UTC, uschischroder commented on src/templates/navbar-template.js
> +      }}'>Download YAML file</button>
Fabian and Victor prefer to be a button instead of a link

2022-08-04 13:17 UTC, enjoythelive1 commented on src/templates/navbar-template.js
> +      }}'>Download YAML file</button>
in a markup sense?

2022-08-08 16:49 UTC, Drafter500 commented on src/templates/navbar-template.js
> +      }}'>Download YAML file</button>
I dont think they care about markup, link could be styled as a button

2022-08-08 16:53 UTC, Drafter500 requested changes
I believe this should be added in ogma using slots:
https://rapidocweb.com/api.html
No need to change rapidoc for this

2022-08-09 15:15 UTC, Drafter500 commented
So, it was pretty much possible to add from Ogma but there 2 issues discovered:
1. I could not place it in exact same position, only right after the logo. This is not nice but still acceptable
2. The whole rapidoc is wrapped in a shadow dom, meaning that if you try to use any class or custom property from it, it won't work. So I ended up copying the entire button class styles. Not nice. 

So having those 2 issues, I am inclined to continue changes on the RapiDoc side.

2022-08-09 15:18 UTC, Drafter500 approved these changes

2022-08-09 15:19 UTC, Drafter500 commented
Thats how it looks like:
![image](https://user-images.githubusercontent.com/24357546/183689309-a3a1efee-2d8e-4357-9aa7-23206e41574e.png)

2022-08-09 15:31 UTC, enjoythelive1 approved these changes

2022-08-09 16:24 UTC, gustavoaz7 approved these changes

2022-08-09 16:53 UTC, merged